server:
  port: 9001
spring:
  application:
    name: order-service
eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:8000/eureka/,http://localhost:9000/eureka/ #注册到多个eureka
      defaultZone: http://localhost:9000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}:${server.port} #自定义eureka中的服务id
    lease-renewal-interval-in-seconds: 5 #服务心跳时间
    lease-expiration-duration-in-seconds: 10 #服务到期时间

#修改ribbon负载均衡策略（默认策略是轮询）  规则：服务名-ribbon-NFLoadBalancerRuleClassName
product-service:
  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule  #随机策略
    #ribbon 请求重试机制
    ConnectTimeout: 250 #ribbon http请求连接超时时间
    ReadTimeout: 1000 #ribbon 数据读取超时时间
    OkToRetryOnAllOperations: true #对所有操作都进行重试
    MaxAutoRetriesNextServer: 1 #切换实例的重试次数
    MaxAutoRetries: 1 #对当前实例的重试次数


