server:
  port: 9001
spring:
  application:
    name: order_service
eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:8000/eureka/,http://localhost:9000/eureka/ #注册到多个eureka
      defaultZone: http://localhost:9000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}:${server.port} #自定义eureka中的服务id
    lease-renewal-interval-in-seconds: 5 #服务心跳时间
    lease-expiration-duration-in-seconds: 10 #服务到期时间
