server:
  port: 9001
spring:
  application:
    name: order_service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/,http://localhost:9000/eureka/ #注册到多个eureka
  instance:
    prefer-ip-address: true
