server:
  port: 9003
spring:
  application:
    name: product-service
eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:8000/eureka/,http://localhost:9000/eureka/ #注册到多个eureka
      defaultZone: http://localhost:9000/eureka/
  instance:
    prefer-ip-address: true

